export const scholarships = [
  {
    name: "Andhra Pradesh Post-Matric Scholarship - Jnanabhumi",
    state: "andhra-pradesh",
    stateLabel: "Andhra Pradesh",
    education: ["intermediate", "degree", "engineering", "pg"],
    categories: ["sc", "st", "bc", "obc", "ebc", "ews", "minority", "kapu", "disabled"],
    genders: ["any"],
    disability: "any",
    maxIncome: 200000,
    minPercentage: 0,
    amount: "Varies as per official rules",
    deadline: "Check official Jnanabhumi portal",
    deadlineDate: "",
    link: "https://jnanabhumi.ap.gov.in/",
    sourceName: "Official Jnanabhumi Portal",
    eligibilityNote: "For eligible Andhra Pradesh post-matric students. Rules may vary by department and category.",
    incomeNote: "Income rules can vary by category. Verify on Jnanabhumi.",
    priority: 95
  },
  {
    name: "Andhra Pradesh Pre-Matric Scholarship - Jnanabhumi",
    state: "andhra-pradesh",
    stateLabel: "Andhra Pradesh",
    education: ["school"],
    categories: ["sc", "st", "bc", "obc", "ebc", "ews", "minority", "kapu", "disabled"],
    genders: ["any"],
    disability: "any",
    maxIncome: 200000,
    minPercentage: 0,
    amount: "Varies as per official rules",
    deadline: "Check official Jnanabhumi portal",
    deadlineDate: "",
    link: "https://jnanabhumi.ap.gov.in/",
    sourceName: "Official Jnanabhumi Portal",
    eligibilityNote: "For eligible school students in Andhra Pradesh. Exact rules should be checked officially.",
    incomeNote: "Income/category rules can vary. Verify before applying.",
    priority: 82
  },
  {
    name: "Telangana ePASS Post-Matric Scholarship",
    state: "telangana",
    stateLabel: "Telangana",
    education: ["intermediate", "degree", "engineering", "pg"],
    categories: ["sc", "st", "bc", "obc", "ebc", "ews", "minority", "disabled"],
    genders: ["any"],
    disability: "any",
    maxIncome: 200000,
    minPercentage: 0,
    amount: "Varies as per official rules",
    deadline: "Check official Telangana ePASS portal",
    deadlineDate: "",
    link: "https://telanganaepass.cgg.gov.in/",
    sourceName: "Official Telangana ePASS Portal",
    eligibilityNote: "For eligible Telangana post-matric students from welfare categories.",
    incomeNote: "Income limits can vary by category and current rules.",
    priority: 95
  },
  {
    name: "Telangana ePASS Pre-Matric Scholarship",
    state: "telangana",
    stateLabel: "Telangana",
    education: ["school"],
    categories: ["sc", "st", "bc", "obc", "ebc", "ews", "minority", "disabled"],
    genders: ["any"],
    disability: "any",
    maxIncome: 200000,
    minPercentage: 0,
    amount: "Varies as per official rules",
    deadline: "Check official Telangana ePASS portal",
    deadlineDate: "",
    link: "https://telanganaepass.cgg.gov.in/",
    sourceName: "Official Telangana ePASS Portal",
    eligibilityNote: "For eligible school students in Telangana.",
    incomeNote: "Verify current income and class rules on ePASS.",
    priority: 82
  },
  {
    name: "National Means-cum-Merit Scholarship Scheme - NMMSS",
    state: "national",
    stateLabel: "National",
    education: ["school"],
    categories: ["general", "sc", "st", "bc", "obc", "minority", "ebc", "ews"],
    genders: ["any"],
    disability: "any",
    maxIncome: 350000,
    minPercentage: 55,
    amount: "Varies as per official rules",
    deadline: "Check NSP / state education department",
    deadlineDate: "",
    link: "https://scholarships.gov.in/",
    sourceName: "National Scholarship Portal",
    eligibilityNote: "For eligible school students. Selection and rules depend on official notification.",
    incomeNote: "Usually income-based. Verify state/NSP instructions.",
    priority: 88
  },
  {
    name: "Central Sector Scheme of Scholarship for College and University Students",
    state: "national",
    stateLabel: "National",
    education: ["degree", "engineering", "pg"],
    categories: ["general", "sc", "st", "bc", "obc", "minority", "ebc", "ews"],
    genders: ["any"],
    disability: "any",
    maxIncome: 450000,
    minPercentage: 80,
    amount: "Varies as per official rules",
    deadline: "Check National Scholarship Portal",
    deadlineDate: "",
    link: "https://scholarships.gov.in/",
    sourceName: "National Scholarship Portal",
    eligibilityNote: "For eligible meritorious college/university students as per official rules.",
    incomeNote: "Income limit and merit rules should be verified on NSP.",
    priority: 86
  },
  {
    name: "AICTE Pragati Scholarship for Girl Students",
    state: "national",
    stateLabel: "National",
    education: ["engineering"],
    categories: ["general", "sc", "st", "bc", "obc", "minority", "ebc", "ews", "kapu"],
    genders: ["female"],
    disability: "any",
    maxIncome: 800000,
    minPercentage: 0,
    amount: "Varies as per official rules",
    deadline: "Check AICTE / NSP portal",
    deadlineDate: "",
    link: "https://www.aicte-india.org/",
    sourceName: "AICTE",
    eligibilityNote: "For eligible girl students pursuing technical education as per AICTE rules.",
    incomeNote: "Family income rules should be checked on official AICTE/NSP notification.",
    priority: 92
  },
  {
    name: "AICTE Saksham Scholarship for Specially Abled Students",
    state: "national",
    stateLabel: "National",
    education: ["engineering"],
    categories: ["general", "sc", "st", "bc", "obc", "minority", "ebc", "ews", "kapu", "disabled"],
    genders: ["any"],
    disability: "yes",
    maxIncome: 800000,
    minPercentage: 0,
    amount: "Varies as per official rules",
    deadline: "Check AICTE / NSP portal",
    deadlineDate: "",
    link: "https://www.aicte-india.org/",
    sourceName: "AICTE",
    eligibilityNote: "For eligible specially abled students pursuing technical education.",
    incomeNote: "Verify latest income/disability conditions in official notification.",
    priority: 92
  },
  {
    name: "Post Matric Scholarship for Minorities",
    state: "national",
    stateLabel: "National",
    education: ["intermediate", "degree", "engineering", "pg"],
    categories: ["minority"],
    genders: ["any"],
    disability: "any",
    maxIncome: 200000,
    minPercentage: 50,
    amount: "Varies as per official rules",
    deadline: "Check NSP",
    deadlineDate: "",
    link: "https://scholarships.gov.in/",
    sourceName: "National Scholarship Portal",
    eligibilityNote: "For eligible minority community students as per official rules.",
    incomeNote: "Income limit can change. Verify on NSP.",
    priority: 84
  },
  {
    name: "Scholarship for Students with Disabilities",
    state: "national",
    stateLabel: "National",
    education: ["school", "intermediate", "degree", "engineering", "pg"],
    categories: ["general", "sc", "st", "bc", "obc", "minority", "ebc", "ews", "kapu", "disabled"],
    genders: ["any"],
    disability: "yes",
    maxIncome: 250000,
    minPercentage: 0,
    amount: "Varies as per official rules",
    deadline: "Check NSP",
    deadlineDate: "",
    link: "https://scholarships.gov.in/",
    sourceName: "National Scholarship Portal",
    eligibilityNote: "For eligible students with benchmark disabilities as per official scheme rules.",
    incomeNote: "Income and disability rules should be verified officially.",
    priority: 88
  }
];
